// ============================================================
// SAPA BPS 1901 IN — Mock / Seed Data
// ============================================================
// DEMO / SAMPLE DATA — Bukan data resmi BPS
// ============================================================

import {
  Dataset,
  DataRecord,
  DataStatus,
  PeriodType,
  User,
  UserRole,
  Category,
  ReviewRequest,
  AuditLog,
  AuditAction,
} from './types';

// --- Categories ---

export const CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Jumlah Penduduk', code: 'POP', description: 'Data kependudukan dan demografi' },
  { id: 'cat-2', name: 'Data Kemiskinan', code: 'POV', description: 'Data kemiskinan dan kesejahteraan' },
  { id: 'cat-3', name: 'Pertumbuhan Ekonomi', code: 'GROWTH', description: 'Data pertumbuhan ekonomi regional' },
  { id: 'cat-4', name: 'Indeks Pembangunan Manusia (IPM)', code: 'HDI', description: 'Indeks pembangunan manusia' },
  { id: 'cat-5', name: 'Tenaga Kerja', code: 'LABOR', description: 'Data ketenagakerjaan dan pengangguran' },
  { id: 'cat-6', name: 'Produk Domestik Regional Bruto (PDRB)', code: 'GRDP', description: 'Data produk domestik regional bruto' },
  { id: 'cat-7', name: 'Indeks Pembangunan Gender (IPG)', code: 'GDI', description: 'Indeks pembangunan gender' },
  { id: 'cat-8', name: 'Angka Partisipasi Sekolah', code: 'EDU', description: 'Data partisipasi pendidikan' },
];

// --- Users ---

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Ahmad Fauzi',
    email: 'ahmad.fauzi@bps.go.id',
    role: UserRole.DATA_ENTRY,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Siti Nurhaliza',
    email: 'siti.nurhaliza@bps.go.id',
    role: UserRole.REVIEWER,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Budi Santoso',
    email: 'budi.santoso@bps.go.id',
    role: UserRole.DATA_ENTRY,
    created_at: '2025-03-15T00:00:00Z',
  },
];

// --- Datasets ---

export const MOCK_DATASETS: Dataset[] = [
  {
    id: 'ds-1',
    code: 'POP-001',
    name: 'Jumlah Penduduk Kabupaten Bangka',
    category: 'Jumlah Penduduk',
    description: 'Data jumlah penduduk Kabupaten Bangka berdasarkan tahun. (DEMO / SAMPLE DATA)',
    definition: 'Jumlah penduduk adalah banyaknya orang yang berdomisili di suatu wilayah pada waktu tertentu.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Jiwa',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.YEARLY,
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-06-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'ds-2',
    code: 'POV-001',
    name: 'Persentase Penduduk Miskin Kabupaten Bangka',
    category: 'Data Kemiskinan',
    description: 'Persentase penduduk miskin di Kabupaten Bangka. (DEMO / SAMPLE DATA)',
    definition: 'Persentase penduduk yang berada di bawah garis kemiskinan terhadap total penduduk.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Persen (%)',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.YEARLY,
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-2',
    created_at: '2026-06-15T08:00:00Z',
    updated_at: '2026-08-30T08:00:00Z',
  },
  {
    id: 'ds-3',
    code: 'GROWTH-001',
    name: 'Laju Pertumbuhan Ekonomi Kabupaten Bangka',
    category: 'Pertumbuhan Ekonomi',
    description: 'Laju pertumbuhan ekonomi Kabupaten Bangka. (DEMO / SAMPLE DATA)',
    definition: 'Laju pertumbuhan Produk Domestik Regional Bruto atas dasar harga konstan.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Persen (%)',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.YEARLY,
    status: DataStatus.PUBLISHED,
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: '2026-07-01T08:00:00Z',
    updated_at: '2026-08-28T08:00:00Z',
  },
  {
    id: 'ds-9',
    code: 'GROWTH-002',
    name: 'Pertumbuhan Ekonomi Triwulanan Lapangan Usaha',
    category: 'Pertumbuhan Ekonomi',
    description: 'Pertumbuhan PDRB Triwulanan menurut lapangan usaha di Kabupaten Bangka.',
    definition: 'Laju pertumbuhan PDRB atas dasar harga konstan per triwulan.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Persen (%)',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.QUARTERLY,
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-07-05T08:00:00Z',
    updated_at: '2026-08-30T08:00:00Z',
  },
  {
    id: 'ds-4',
    code: 'HDI-001',
    name: 'Indeks Pembangunan Manusia (IPM) Kabupaten Bangka',
    category: 'Indeks Pembangunan Manusia (IPM)',
    description: 'Data IPM Kabupaten Bangka. (DEMO / SAMPLE DATA)',
    definition: 'Indeks komposit yang mengukur kualitas pembangunan manusia melalui dimensi kesehatan, pendidikan, dan standar hidup.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Indeks',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.YEARLY,
    status: DataStatus.DRAFT,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-07-15T08:00:00Z',
    updated_at: '2026-08-25T08:00:00Z',
  },
  {
    id: 'ds-5',
    code: 'LABOR-001',
    name: 'Tingkat Pengangguran Terbuka Kabupaten Bangka',
    category: 'Tenaga Kerja',
    description: 'Data tingkat pengangguran terbuka Kabupaten Bangka. (DEMO / SAMPLE DATA)',
    definition: 'Persentase pengangguran terhadap angkatan kerja.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Persen (%)',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.YEARLY,
    status: DataStatus.REVIEW,
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: '2026-08-01T08:00:00Z',
    updated_at: '2026-08-20T08:00:00Z',
  },
  {
    id: 'ds-6',
    code: 'GRDP-001',
    name: 'PDRB Atas Dasar Harga Berlaku Kabupaten Bangka',
    category: 'Produk Domestik Regional Bruto (PDRB)',
    description: 'PDRB atas dasar harga berlaku Kabupaten Bangka. (DEMO / SAMPLE DATA)',
    definition: 'Jumlah nilai tambah bruto yang dihasilkan oleh seluruh unit usaha dalam suatu wilayah.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Miliar Rupiah',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.YEARLY,
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-2',
    created_at: '2026-08-05T08:00:00Z',
    updated_at: '2026-08-31T08:00:00Z',
  },
  {
    id: 'ds-7',
    code: 'GDI-001',
    name: 'Indeks Pembangunan Gender Kabupaten Bangka',
    category: 'Indeks Pembangunan Gender (IPG)',
    description: 'Data IPG Kabupaten Bangka. (DEMO / SAMPLE DATA)',
    definition: 'Rasio IPM perempuan terhadap IPM laki-laki yang mengukur kesetaraan pembangunan antar gender.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Indeks',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.YEARLY,
    status: DataStatus.DRAFT,
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: '2026-08-10T08:00:00Z',
    updated_at: '2026-08-15T08:00:00Z',
  },
  {
    id: 'ds-8',
    code: 'EDU-001',
    name: 'Angka Partisipasi Sekolah Kabupaten Bangka',
    category: 'Angka Partisipasi Sekolah',
    description: 'Data angka partisipasi sekolah Kabupaten Bangka per jenjang. (DEMO / SAMPLE DATA)',
    definition: 'Proporsi anak sekolah pada suatu kelompok umur tertentu terhadap penduduk kelompok umur yang bersesuaian.',
    geographic_scope: 'Kabupaten Bangka',
    unit: 'Persen (%)',
    source: 'BPS Kabupaten Bangka',
    period_type: PeriodType.YEARLY,
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-08-12T08:00:00Z',
    updated_at: '2026-08-29T08:00:00Z',
  },
];

// --- Data Records ---

export const MOCK_RECORDS: DataRecord[] = [
  // Jumlah Penduduk (ds-1)
  ...[2020, 2021, 2022, 2023, 2024, 2025].map((year, i) => ({
    id: `rec-pop-${year}`,
    dataset_id: 'ds-1',
    indicator: 'Jumlah Penduduk',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [297100, 300200, 306200, 310100, 315400, 320500][i],
    unit: 'Jiwa',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-06-01T08:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
    is_deleted: false,
  })),

  // Kemiskinan (ds-2)
  ...[2020, 2021, 2022, 2023, 2024, 2025].map((year, i) => ({
    id: `rec-pov-${year}`,
    dataset_id: 'ds-2',
    indicator: 'Persentase Penduduk Miskin',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [5.04, 4.98, 4.72, 4.55, 4.41, 4.28][i],
    unit: 'Persen (%)',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-2',
    created_at: '2026-06-15T08:00:00Z',
    updated_at: '2026-08-30T08:00:00Z',
    is_deleted: false,
  })),

  // Pertumbuhan Ekonomi (ds-3)
  ...[2020, 2021, 2022, 2023, 2024, 2025].map((year, i) => ({
    id: `rec-growth-${year}`,
    dataset_id: 'ds-3',
    indicator: 'Pertumbuhan Ekonomi',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [-2.31, 3.84, 4.52, 4.78, 5.01, 5.15][i],
    unit: 'Persen (%)',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.PUBLISHED,
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: '2026-07-01T08:00:00Z',
    updated_at: '2026-08-28T08:00:00Z',
    is_deleted: false,
  })),

  // Pertumbuhan Ekonomi Triwulanan (ds-9)
  ...['2025-Q1', '2025-Q2', '2025-Q3'].map((q, i) => ({
    id: `rec-growth-q-${q}`,
    dataset_id: 'ds-9',
    indicator: 'Pertumbuhan Ekonomi Triwulanan',
    region: 'Kabupaten Bangka',
    period: q,
    value: [4.85, 5.12, 4.96][i],
    unit: 'Persen (%)',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-07-05T08:00:00Z',
    updated_at: '2026-08-30T08:00:00Z',
    is_deleted: false,
  })),

  // IPM (ds-4)
  ...[2020, 2021, 2022, 2023, 2024].map((year, i) => ({
    id: `rec-hdi-${year}`,
    dataset_id: 'ds-4',
    indicator: 'Indeks Pembangunan Manusia',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [69.79, 70.22, 70.95, 71.38, 71.82][i],
    unit: 'Indeks',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.DRAFT,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-07-15T08:00:00Z',
    updated_at: '2026-08-25T08:00:00Z',
    is_deleted: false,
  })),

  // Tenaga Kerja (ds-5)
  ...[2021, 2022, 2023, 2024].map((year, i) => ({
    id: `rec-labor-${year}`,
    dataset_id: 'ds-5',
    indicator: 'Tingkat Pengangguran Terbuka',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [5.83, 5.42, 5.11, 4.95][i],
    unit: 'Persen (%)',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.REVIEW,
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: '2026-08-01T08:00:00Z',
    updated_at: '2026-08-20T08:00:00Z',
    is_deleted: false,
  })),

  // PDRB (ds-6)
  ...[2020, 2021, 2022, 2023, 2024, 2025].map((year, i) => ({
    id: `rec-grdp-${year}`,
    dataset_id: 'ds-6',
    indicator: 'PDRB Atas Dasar Harga Berlaku',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [18245.5, 19102.3, 20534.7, 21890.2, 23150.8, 24520.1][i],
    unit: 'Miliar Rupiah',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-2',
    created_at: '2026-08-05T08:00:00Z',
    updated_at: '2026-08-31T08:00:00Z',
    is_deleted: false,
  })),

  // IPG (ds-7)
  ...[2021, 2022, 2023].map((year, i) => ({
    id: `rec-gdi-${year}`,
    dataset_id: 'ds-7',
    indicator: 'Indeks Pembangunan Gender',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [88.45, 88.92, 89.18][i],
    unit: 'Indeks',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.DRAFT,
    created_by: 'user-3',
    updated_by: 'user-3',
    created_at: '2026-08-10T08:00:00Z',
    updated_at: '2026-08-15T08:00:00Z',
    is_deleted: false,
  })),

  // Angka Partisipasi Sekolah (ds-8)
  ...[2021, 2022, 2023, 2024].map((year, i) => ({
    id: `rec-edu-sd-${year}`,
    dataset_id: 'ds-8',
    indicator: 'APS SD (7-12 tahun)',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [99.52, 99.61, 99.68, 99.72][i],
    unit: 'Persen (%)',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-08-12T08:00:00Z',
    updated_at: '2026-08-29T08:00:00Z',
    is_deleted: false,
  })),
  ...[2021, 2022, 2023, 2024].map((year, i) => ({
    id: `rec-edu-smp-${year}`,
    dataset_id: 'ds-8',
    indicator: 'APS SMP (13-15 tahun)',
    region: 'Kabupaten Bangka',
    period: String(year),
    value: [95.18, 95.42, 95.87, 96.12][i],
    unit: 'Persen (%)',
    notes: 'DEMO / SAMPLE DATA',
    source: 'BPS Kabupaten Bangka',
    status: DataStatus.PUBLISHED,
    created_by: 'user-1',
    updated_by: 'user-1',
    created_at: '2026-08-12T08:00:00Z',
    updated_at: '2026-08-29T08:00:00Z',
    is_deleted: false,
  })),
];

// --- Review Requests ---

export const MOCK_REVIEWS: ReviewRequest[] = [
  {
    id: 'rev-1',
    dataset_id: 'ds-5',
    dataset_name: 'Tingkat Pengangguran Terbuka Kabupaten Bangka',
    record_ids: ['rec-labor-2021', 'rec-labor-2022', 'rec-labor-2023', 'rec-labor-2024'],
    description: 'Penambahan data tingkat pengangguran terbuka tahun 2021–2024',
    submitted_by: 'user-3',
    submitted_by_name: 'Budi Santoso',
    submitted_at: '2026-08-20T10:00:00Z',
    status: 'PENDING',
  },
];

// --- Audit Logs ---

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    entity_type: 'dataset',
    entity_id: 'ds-1',
    entity_name: 'Jumlah Penduduk Kabupaten Bangka',
    action: AuditAction.CREATE,
    changes: [],
    user_id: 'user-1',
    user_name: 'Ahmad Fauzi',
    created_at: '2026-06-01T08:00:00Z',
  },
  {
    id: 'log-2',
    entity_type: 'record',
    entity_id: 'rec-pop-2025',
    entity_name: 'Jumlah Penduduk 2025',
    action: AuditAction.CREATE,
    changes: [
      { field: 'value', old_value: null, new_value: 320500 },
    ],
    user_id: 'user-1',
    user_name: 'Ahmad Fauzi',
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'log-3',
    entity_type: 'dataset',
    entity_id: 'ds-1',
    entity_name: 'Jumlah Penduduk Kabupaten Bangka',
    action: AuditAction.PUBLISH,
    changes: [
      { field: 'status', old_value: 'REVIEW', new_value: 'PUBLISHED' },
    ],
    user_id: 'user-2',
    user_name: 'Siti Nurhaliza',
    created_at: '2026-09-01T09:00:00Z',
  },
  {
    id: 'log-4',
    entity_type: 'record',
    entity_id: 'rec-pov-2025',
    entity_name: 'Persentase Penduduk Miskin 2025',
    action: AuditAction.UPDATE,
    changes: [
      { field: 'value', old_value: 4.35, new_value: 4.28 },
    ],
    user_id: 'user-1',
    user_name: 'Ahmad Fauzi',
    reason: 'Revisi data resmi BPS',
    created_at: '2026-08-30T14:00:00Z',
  },
  {
    id: 'log-5',
    entity_type: 'dataset',
    entity_id: 'ds-5',
    entity_name: 'Tingkat Pengangguran Terbuka Kabupaten Bangka',
    action: AuditAction.SUBMIT_REVIEW,
    changes: [
      { field: 'status', old_value: 'DRAFT', new_value: 'REVIEW' },
    ],
    user_id: 'user-3',
    user_name: 'Budi Santoso',
    created_at: '2026-08-20T10:00:00Z',
  },
];
